### ISSUE TITLE
feature request(Antibot)

### ISSUE THREAD

**Issue by Suger114514** [Seyz123/SxClient#2]
I request Antibot because KillAura attacks npc(bot) by mistake.
I am annoyed by the act

It can't attack npc(bot).
Probably, it come true by comparing entity's size.

I am Japanese.
So, my English is bad.
Sorry

Please add this feature.

**Comment by Seyz123** [comment]
Size are for killaura and aimbot bots, after basic NPCs, that need to check entities's names, I'll do some tests on and maybe that'll be added. 😉

**Comment by Suger114514** [comment]
Thank you.

**Comment by Seyz123** [comment]
Need more work.
