### ISSUE TITLE
Feature Request (Bypass Glide/Fly for Hive)

### ISSUE THREAD

**Issue by TheTerrarian101** [Seyz123/SxClient#3]
Recently TheHive patched ForceFly which sucks as I now have to use other clients for the bypass glide which also means no kill-aura which is something that I need. I was wondering if you can add a bypass glide/fly meant for TheHive MCBE server so i can go back to clapping. More people will also use your client.

P.S Good luck and hopefully they re-add debugging symbols.

Have a great day/night

**Comment by TheTerrarian101** [comment]
> Recently TheHive patched ForceFly which sucks as I now have to use other clients for the bypass glide which also means no kill-aura which is something that I need. I was wondering if you can add a bypass glide/fly meant for TheHive MCBE server so i can go back to clapping. More people will also use your client.
> 
> P.S Good luck and hopefully they re-add debugging symbols.
> 
> Have a great day/night

Can you also add Tracers? Would be helpful.

**Comment by Seyz123** [comment]
I'll look for Hive, and tracers, I was working on it.

**Comment by Seyz123** [comment]
Need more intention to find bypass
