### ISSUE TITLE
Feature Request: Change Air Speed

### ISSUE THREAD

**Issue by TheTerrarian101** [Seyz123/SxClient#8]
A module (maybe with a slider or number input) where you can change the movement speed of when you are in the air, works well with AirJump as it bypasses Hive and the speed can make things easier for speed when i'm clapping them snitches in treasure wars.

Have a great day/night.

**Comment by saini999** [comment]
Yeah AirInfinity should have it
So that you can use it in cc 
Im still waiting for scaffold...

**Comment by TheTerrarian101** [comment]
> Yeah AirInfinity should have it
> So that you can use it in cc
> Im still waiting for scaffold...

I have no idea if scaffold will be added or not but hopefully it does.

**Comment by Seyz123** [comment]
In next update.
